Add files via upload
Fixed windows download from Microsoft site with win 10 insider build

diff --git a/scripts/utils/common/tools/download-windows-iso b/scripts/utils/common/tools/download-windows-iso
--- a/scripts/utils/common/tools/download-windows-iso
+++ b/scripts/utils/common/tools/download-windows-iso
@@ -5,7 +5,44 @@
 # Usage: `./download-windows-iso "/path/to/where/you/want/to/save/the/windows.iso" "x64"` 
 #####################################################################################################
 
+WIN10_IMG_DESTINATION="$1"#!/usr/bin/env bash
+
+#####################################################################################################
+# Downloads a Windows 10 ISO from Microsoft
+# Usage: `./download-windows-iso "/path/to/where/you/want/to/save/the/windows.iso" "x64"` 
+#####################################################################################################
+
 WIN10_IMG_DESTINATION="$1"
+WIN10_IMG_ARCH="$2"
+echo "$WIN10_IMG_DESTINATION"
+
+if [[ "$WIN10_IMG_ARCH" == "x86" ]] || [[ "$WIN10_IMG_ARCH" == "i386" ]] ; then
+    echo "Retrieving the x86 Windows 10 iso URL..."
+    WINDOWS_10_ISO_URL=$(curl -LsI -o /dev/null -w %{url_effective} "https://files.rg-adguard.net/file/2eff1a2b-8fb7-4ac1-6821-1f4c4f734a41")
+else
+    echo "Retrieving the x64 Windows 10 iso URL..."
+    WINDOWS_10_ISO_URL=$(curl -LsI -o /dev/null -w %{url_effective} "https://files.rg-adguard.net/file/2eff1a2b-8fb7-4ac1-6821-1f4c4f734a41")
+fi
+
+echo "$WINDOWS_10_ISO_URL"
+echo "Making sure the URL comes from a trusted Microsoft domain..."
+if [[ $WINDOWS_10_ISO_URL == https://*.microsoft.com/* ]] ; then
+    echo "Downloading the Windows 10 installation iso..."
+    if [ ! -f "${WIN10_IMG_DESTINATION}" ]; then
+        if wget "${WINDOWS_10_ISO_URL}" --no-check-certificate -c -O "${WIN10_IMG_DESTINATION}.part"; then
+            mv "${WIN10_IMG_DESTINATION}.part" "${WIN10_IMG_DESTINATION}"
+        else
+            echo "Download failed. Please try again or download the Windows 10 iso manually."
+            exit 1
+        fi
+    else
+        echo "Skipping download because the Windows ISO already exists: ${WIN10_IMG_DESTINATION}"
+    fi
+else
+    echo "URL validation failed. Please download the Windows 10 iso manually."
+    exit 1
+fi
+
 WIN10_IMG_ARCH="$2"
 echo "$WIN10_IMG_DESTINATION"
 
